Sensor:
  hostname: 10.0.81.96
  port: 22
  username: root
  password: prs@2018
  pcap_path: /home/aiqinghua/pcap/

kafka:
  kafka_server_ip: 10.0.81.93
  kafka_port: 9091
  kafka_cert_path: certs/kafka
  kafka_consumer_timeout: 180  # 消费数据超时时间，单位秒
  topic:
    - tophant.etl.http
    - tophant.etl.dns
    - tophant.etl.tcp
    - tophant.etl.udp
    - tophant.etl.icmp
#    - tophant.etl.file
    - tophant.etl.mail
    - tophant.etl.protocol

  group_id: test_id
#  kafka_http_msg: msg/kafka.txt
  kafka_msg:
    - msg/kafka_http.txt
    - msg/kafka_dns.txt
    - msg/kafka_tcp.txt
    - msg/kafka_udp.txt
    - msg/kafka_icmp.txt
#    - msg/kafka_file.txt
    - msg/kafka_mail.txt
    - msg/kafka_protocol.txt

logs:
  data_comparison_logs_path:
    - logs/data_comparison.log
  Comparison_results:
    - logs/Comparison_results.log

pcap:
  config_path:
    - pcap_conf/http.conf
    - pcap_conf/dns.conf
    - pcap_conf/tcp.conf
    - pcap_conf/udp.conf
    - pcap_conf/icmp.conf
#    - pcap_conf/file.conf
    - pcap_conf/smtp.conf
    - pcap_conf/pop3.conf
    - pcap_conf/imap.conf
    - pcap_conf/arp.conf
    - pcap_conf/dhcp.conf
    - pcap_conf/ftp.conf
    - pcap_conf/rarp.conf
    - pcap_conf/syslog.conf
    - pcap_conf/telnet.conf
    - pcap_conf/ssl.conf
    - pcap_conf/mysql.conf
    - pcap_conf/socks.conf
    - pcap_conf/snmp.conf
    - pcap_conf/llmnr.conf
    - pcap_conf/ldap.conf
    - pcap_conf/rdp.conf
  CONF_DIR: pcap_conf
  PCAPS_DIR: pcap